version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=simple_bank
    ports:
      - "5431:5432"
    volumes:
      - data-volume:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
      - "9090:9090"
    environment:
      - DB_SOURCE=postgresql://postgres:12345@postgres:5432/simple_bank?sslmode=disable
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - postgres 
      - redis  
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"] 
    command: ["/app/main"]

volumes:
  data-volume:
