version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=simple_bank
    ports:
      - "5431:5432"
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    environment:
      - DB_SOURCE=postgresql://postgres:12345@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres   
    entrypoint: ["/app/wait-for.sh","postgres:5432","--","/app/start.sh"] 
    command: ["/app/main"]
     
